### ISSUE TITLE
ping: socket: operation not permitted inside Docker

### ISSUE THREAD

**Issue by ManOki** [OliveTin/OliveTin#46]
**Describe the bug**
I run OliveTin inside docker-compose with a pretty standard configuration. The default Dockerimage does not allow users, i.e., OliveTin as user who executes the shell commands, to open an icmp socket for ping requests. So ping actions are not possible.

This behaviour is the same if executed directly on the shell inside the docker container and is already mentioned in #28 [(comment)](https://github.com/OliveTin/OliveTin/issues/28#issuecomment-1005034028_) .

I suppose the base image `docker.io/amd64/fedora` has a very strict security concept, as opening a socket requires root permission by default. The common way to allow users ping commands is to set file capabilites (similiar to suid bit).

**Workaround**
Enter root shell of the docker container and run `setcap cap_net_raw+ep /bin/ping`.

**Fix**
Run inside the Dockerfile `setcap cap_net_raw+ep /bin/ping` (or use another base image).

**Test**
You can query the file capabilities of ping via `getcap /bin/ping`. There are no ones for OliveTin docker container, but the mentioned `cap_net_raw=ep` on regular linux user systems.

**Comment by jamesread** [comment]
Hey @ManOki, thanks for raising this issue, you've taught me a little more about capabilities than I knew before - not heard of setcap/getcap before. 

You're right that many folks would expect ping to work inside the container, I certainly will consider adjusting that within the Dockerfile - but would also want to run some tests to check that's all that is needed.

This should also be documented as well, just incase others want to build their own containers too. 

So, thanks for reporting this - it's accepted. Here's a action plan for a more permanent fix, and a workaround for now; 

**Action plan**
- [ ] Adjust the dockerfile to add setcap on ping
- [ ] Write a test to check that this works. 
- [ ] Documentation covering setcap/get for others that want to build their own dockerfile. 

**Workaround**

For now, running the container as a root with `--privileged` would make ping work.
